/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SalapangPackage;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;

public class dashboards extends javax.swing.JFrame {

    /**
     * Creates new form dashboards
     */
    public dashboards() {
        initComponents();
        setLocationRelativeTo(null);
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lusername2 = new javax.swing.JLabel();
        txtfullname = new javax.swing.JTextField();
        Lusername3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        Lusername4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        Lusername5 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        bttnupdate = new javax.swing.JButton();
        bttndelete = new javax.swing.JButton();
        bttlogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        maintable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 169, 205));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");

        Lusername2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lusername2.setForeground(new java.awt.Color(255, 255, 255));
        Lusername2.setText("Full Name");

        txtfullname.setBackground(new java.awt.Color(240, 248, 255));
        txtfullname.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtfullname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        Lusername3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lusername3.setForeground(new java.awt.Color(255, 255, 255));
        Lusername3.setText("Email");

        txtemail.setBackground(new java.awt.Color(240, 248, 255));
        txtemail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtemail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        Lusername4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lusername4.setForeground(new java.awt.Color(255, 255, 255));
        Lusername4.setText("Username");

        txtusername.setBackground(new java.awt.Color(240, 248, 255));
        txtusername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtusername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        Lusername5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lusername5.setForeground(new java.awt.Color(255, 255, 255));
        Lusername5.setText("Password");

        txtpassword.setBackground(new java.awt.Color(240, 248, 255));
        txtpassword.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtpassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        bttnupdate.setBackground(new java.awt.Color(0, 0, 128));
        bttnupdate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bttnupdate.setForeground(new java.awt.Color(255, 255, 255));
        bttnupdate.setText("Update");
        bttnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnupdateActionPerformed(evt);
            }
        });

        bttndelete.setBackground(new java.awt.Color(0, 0, 128));
        bttndelete.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bttndelete.setForeground(new java.awt.Color(255, 255, 255));
        bttndelete.setText("Delete");
        bttndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttndeleteActionPerformed(evt);
            }
        });

        bttlogout.setBackground(new java.awt.Color(0, 0, 128));
        bttlogout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bttlogout.setForeground(new java.awt.Color(255, 255, 255));
        bttlogout.setText("Log Out");
        bttlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bttlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lusername2)
                                        .addComponent(Lusername3)
                                        .addComponent(Lusername4)
                                        .addComponent(Lusername5))
                                    .addGap(132, 132, 132))
                                .addComponent(txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(Lusername2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lusername3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lusername4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lusername5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(bttnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        maintable.setBackground(new java.awt.Color(255, 255, 255));
        maintable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maintable.setForeground(new java.awt.Color(0, 0, 0));
        maintable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Full Name", "Email", "Username", "Password"
            }
        ));
        maintable.setToolTipText("");
        maintable.setAutoscrolls(false);
        maintable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maintableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(maintable);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Welcome to April Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(99, 99, 99)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnupdateActionPerformed
        String fullName = txtfullname.getText();
        String email = txtemail.getText();
        String username = txtusername.getText();
        String password = txtpassword.getText();
        
        try {
            String url = "jdbc:mysql://localhost:3306/salapang_db";
            java.sql.Connection conn = java.sql.DriverManager.getConnection(url, "root", "");

            String sql = "UPDATE users SET fullname=?, email=?, password=? WHERE username=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, fullName);
            pst.setString(2, email);
            pst.setString(3, password); 
            pst.setString(4, username);

            int updated = pst.executeUpdate();
            if (updated > 0) {
                JOptionPane.showMessageDialog(this, "User Record Updated!");
                showData(); // I refresh ang table 
                txtusername.setEditable(true); // para magamit sa sunod
            }
                conn.close();
            
        }catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Update Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttnupdateActionPerformed

    private void bttndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttndeleteActionPerformed
        String user = txtusername.getText();

        if (user.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a user from the table first.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user?", "Warning", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String url = "jdbc:mysql://localhost:3306/salapang_db";
                java.sql.Connection conn = java.sql.DriverManager.getConnection(url, "root", "");

                String sql = "DELETE FROM users WHERE username=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, user);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "User removed from records");

                txtusername.setText("");
                txtpassword.setText("");
                showData();
                txtusername.setEditable(true);

                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Delete Error" + e.getMessage());
            }
        }
    }//GEN-LAST:event_bttndeleteActionPerformed

    private void bttlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttlogoutActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Are you sure?", "Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.YES_OPTION) {
            //mobalik sa login nga jframe
            Login log = new Login();
            log.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_bttlogoutActionPerformed

    private void maintableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintableMouseClicked
        DefaultTableModel model = (DefaultTableModel) maintable.getModel();
        int i = maintable.getSelectedRow();

        txtfullname.setText(model.getValueAt(i, 0).toString());
        txtemail.setText(model.getValueAt(i, 1).toString());
        txtusername.setText(model.getValueAt(i, 2).toString());
        txtpassword.setText(model.getValueAt(i, 3).toString());

        //I disable and username during pag edit para dili ma change ang ID
        txtusername.setEditable(false);
    }//GEN-LAST:event_maintableMouseClicked

        public void showData(){
        try{
            //I setup and connection sa database
             String url = "jdbc:mysql://localhost:3306/salapang_db";
            java.sql.Connection conn = java.sql.DriverManager.getConnection(url, "root", "");

            //Iandam ang table model
            DefaultTableModel model = (DefaultTableModel) maintable.getModel();
            model.setRowCount(0);
            
            //execution sa query
            String sql = "SELECT fullname, email, username, password FROM users";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            
            //mag loop sa database result dayun I add sa main table
            while (rs.next()) {
                String fullname, email, username, password;
                
                fullname = rs.getString("fullname");
                email = rs.getString("email");
                username = rs.getString("username");
                password = rs.getString("password");
                
                //Idugang ang data as new row sa main table
                Object[] row = {fullname, email, username,password};
                model.addRow(row);
            }
            conn.close();
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error loading data:" + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lusername2;
    private javax.swing.JLabel Lusername3;
    private javax.swing.JLabel Lusername4;
    private javax.swing.JLabel Lusername5;
    private javax.swing.JButton bttlogout;
    private javax.swing.JButton bttndelete;
    private javax.swing.JButton bttnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable maintable;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfullname;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
